### ISSUE TITLE
Replace BoxT with VariableBounds

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#1]
Currently we are using BoxT (map<Variable, Interval>) inside of each ICPState to store the current box.
Use the already implemented VariableBounds class instead. Since that class can already handle adding and removing clauses, use one instance of it in the ICPPDWModule instead of one in every ICPState.

**Comment by DavidWz** [comment]
Also add the VariableBounds.add(constraint) in addConstraint and VariableBounds.remove(constraint) in removeConstraint of ICPPDWModule.

Also, maybe we can replace the createInitialSlackVariableBounds method with a call to VariableBounds.add(SlackConstraint) during linearization.

**Comment by kperun** [comment]
Hey @DavidWz , this issue has been solved. For each formula which is handed over to informCore(), we extract the corresponding constraint (up to now no changes), and add it to the VariableBounds object. You can retrieve the corresponding bounds it by means of getIntervalMap() (e.g.). During the processing of slack variables, we do the same thing and add "slackConstraints" to the set of bounds, namely mBounds (the VariableBounds variable). Slack variables are not constrainted as it should be.
