### ISSUE TITLE
Fix ICPContractionCandidate::getContractedInterval

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#12]
This method completely ignores the second interval right now. This might need some more attention.

**Comment by kperun** [comment]
There is also somehow a problem with "map.at(mVariable)" (line 39), which results in out of bound whenever used in "contract()" of ICPTree. @DavidWz please take a loot at it.

**Comment by DavidWz** [comment]
Fixed, but calculateBestCandidate is not working properly. It does not return the best candidate. You should revise your algorithm...

**Comment by kperun** [comment]
@DavidWz calculateBestCandidate() has been update and checked. Please take a look at it.
