### ISSUE TITLE
Make return value of getBestCandidate optional

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#14]
If every gain is too small, we should do an autonomous split.
To this end, getBestCandidate should return an empty optional if every gain is too small.
Inside the contract() method, stop contracting if an empty optional gets returned from getBestCandidate.

Later, we should not stop contracting but do a split.

**Comment by kperun** [comment]
@DavidWz getBestCandidate now returns an optional int representing the index of the best candidate in the list of handed over contraction candidates. contract() has also been updated and now returns false whenever a too small gain has been achieved. Please review the code if possible.
