### ISSUE TITLE
Handle solution after returning SAT

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#15]
The model created in checkCore is simply ignored after it was checked. 
It should probably be saved and updated according to the updateModel function.

**Comment by kperun** [comment]
@DavidWz implemented. Now in ICPPDWModel the mFoundModel variable stores an optional model, whenever such a model has been found in checkCore(). Whenever updateModel() is called and the satsolver() has the status SAT, this model is handed over as a satisfying assignment.
