### ISSUE TITLE
Handle conflicting constraints after returning UNSAT

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#17]
Similar to issue #15 .
We need to generate an unsat core by using the conflict reasons set of ICPTree in ICPPDWModule::updateModel.

**Comment by kperun** [comment]
@DavidWz it looks like updateModel() is not supposed to take care of this job. This method is only called whenever a SAT has been returned by the checkCore() routine. Now,  if unsat has been returned, we have to proceed in a different way.

**Comment by kperun** [comment]
@DavidWz CheckCore() further extended. All constraints which are returned by getConflictingConstraints() are now used as a infeasible subset by retrieving the corresponding formulas. This set is then handed over to mInfeasibleSet variable of the Module (super class) which - I guess - is then inspected by the frontend.

**Comment by kperun** [comment]
@DavidWz Here, it is probably interesting to know if the set of conflicting constraints as returned by getConflictingConstraints() is already the smallest one or if it need further processing.
Edit: It looks like this problem is related to #18 .
