### ISSUE TITLE
Use Contractor class for contraction

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#2]
Use the already implemented Contractor class to solve a polynomial for one variable and calculate a new box for that variable.
To that end, create a new member variable inside of ICPContractionCandidate of type Contractor. Inside of the constructor of ICPContractionCandidate, create such a contractor with the given polynomial and variable (and maybe let it already solve the polynomial for that variable). Also create a new method which takes a Box / VariableBounds object and returns the contracted Interval for that variable. (maybe also update it in the VariableBounds object instead of returning)

**Comment by DavidWz** [comment]
Regarding the update of VariableBounds with the new contracted Interval:
Apparently you can't directly set an interval for a variable, so I think we would need to do the following:
Create two new constraints from the contracted interval: one of the form x >= lowerBound, another of the form x <= upperBound (or >, <, if the interval is open). Then, we could add those new constraints to the VariableBounds.

**Comment by DavidWz** [comment]
I would split this into two methods:
Interval getContractedInterval(VariableBounds&)
and
void applyContraction(VariableBounds&)

**Comment by kosti1992** [comment]
@DavidWz  TestContraction.cpp seems to be quite promising here.

**Comment by DavidWz** [comment]
The basic getContraction method is implemented, however it only works for equalities right now.
We need to extend this to inequalities as well (<=).
