### ISSUE TITLE
Implement ICPState::getBestSplitVariable()

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#21]
If all gains are too small, we need to manually split an interval in ICPTree::contract (if an empty optional was returned by getBestContractionCandidate).

To this end, we need to choose a variable we want to split on.
Create a new method carl::Variable ICPState::getBestSplitVariable() which picks the best variable,
i.e. the biggest interval.

**Comment by kperun** [comment]
@Verdict7 , @DavidWz : done. This method now returns the variable with the biggest interval. Please review the code and close the issue.
