### ISSUE TITLE
Improve Settings

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#24]
Rename thresholds (maybe other values too):
TargetDiameter
GainThreshold

Also use template for settings.

**Comment by Verdict7** [comment]
Used Settings template for ICPState and ICPTree. 
@kperun and @DavidWz if you know any other places that use the settings please go ahead and change them accordingly. 
Otherwise I will close this issue.

**Comment by DavidWz** [comment]
I added a ICPUtil class which used the settings, so I templated it too.
I think there's nothing else that uses the settings, so go ahead and close it.
