### ISSUE TITLE
Enable Statistics

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#26]
Like counting splits, nodes etc

**Comment by kperun** [comment]
@Verdict7 statistics have been implemented. Currently, the following data is stored and printed to the standard output:  number of performed splits, number of checked nodes, number of wrong solution guesses, number of performed contractions, the overall contraction diameter, average contraction gain, number of performed contractions and finally the number of SAT<>SMTRAT iterations (i.e. how often did we returned to the frontend). If you want to print the statistics, set the corresponding option in ccmake and execute smtrat with -s, e.g. ./smtrat -s NAME/OF/FILE . If you would like to have more statistics, describe them briefly and I will implement them.

**Comment by kperun** [comment]
I'm currently reviewing the code and it seems that the statistics system sometimes behaves not as intended. E.g. the con_bug_text example yields a negative average gain, which seems to be wrong. Maybe it has something to do with @Verdict7 latest bugfix where we deal with empty intervals and their contraction?
