### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#27]
We are using way too much std::cout, someone should look at logging and change output. 
cout should only be used when logging is enabled.

**Comment by kperun** [comment]
@Verdict7 , @DavidWz done. Now, messages are printed to the console only if LOGGING has been enabled in ccmake, otherwise no output is generated. Please review the code and close the issue.

**Comment by Verdict7** [comment]
This should be turned into a define that only logs ICPPDW module information. 
(ifdef PDW_DEBUG_1 cout << endl; for example similar to the ICPModule logging).
The very verbose smtrat stuff is not helpful in my opinion.

**Comment by kperun** [comment]
After a short discussion with DavidWz we come to the following conclusion: Instead of replacing our calls to the logger with defs and cout, we will deactivate the logging system in the sat solver by undefining the corresponding def.

**Comment by kperun** [comment]
@Verdict7 this issue has been resolved in the last push. Now, only our stuff is printed to the screen (except some information regarding which constraints are currently checked). Inform me if you would like to have less output.
