### ISSUE TITLE
Improve getBestSplitVariable

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#29]
If you run the solver on the polypaver example, you will see it splits the biggest interval of the slack variable a lot of times.

Maybe we can improve this behavior by choosing the biggest interval of **original** variables. Should we even split slack variable bounds? 

This needs testing.

**Comment by Verdict7** [comment]
@kperun Last commit did not compile, there was a "{" missing after the if. Also: Contraction should still be possible with slack variables, only splitting should prefer original variables.
