### ISSUE TITLE
Improve getBestContractionCandidate by using a history alpha

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#32]
Refer to the ICP slides from the lecture.
A further heuristic is to add a weight to the gain of contraction candidates which stores how often that candidate has been used in the past.
Don't forget to add the weight in the settings.

**Comment by kperun** [comment]
@DavidWz , @Verdict7 issue has been solved. Now each contraction candidate contains a weight which is used for reinforced learning and updated in each getBestContractionCandidate() run. Please review the code and close the issue.
