### ISSUE TITLE
Termination due to number of splits ignored

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#39]
The simple iterative test does not terminate, since the split termination condition is ignored. 
Adding the following line to ICPState.cpp:
158   bool ICPState<Settings>::isTerminationConditionReached() {
+ 171     cout << "Split: " << computeNumberOfSplits() << "/" << Settings::maxSplitNumber << endl;
Will give the following output: 
Split: 6297/100
Split: 6297/100
and so on...

**Comment by DavidWz** [comment]
Fixed.
