### ISSUE TITLE
Make target diameter relative?

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#48]
Currently the target diameter is given in terms of absolute value.
If we have a target diameter of 0.01, then this makes sense for numbers in single digits, but not for intervals of size [-10.000, 9.900].

Maybe it would be better to see the target diameter as a relative number, e.g. 0.1 means 10%.
This would lead to termination in both cases, [0.9,1] and [900, 1000].

Discussion is required.

**Comment by kperun** [comment]
@DavidWz issue has been solved in the latest push. Now, whenever informCore() is called, we generate the desired target diameter by initial diameter times a constant as stored in the settings (e.g. 10%). For each variable, we store such a desired interval and check in isTerminationConditionReached() if for all variables we have reached their individual desired target diameter. Please review the code and close the issue.

**Comment by DavidWz** [comment]
@kperun This makes absolutely no sense.
The initial diameter for original variables is always 2000. The initial diameter for slack variables is always infinity. Your change even introduces unnecessary data structures...

Please revert the changes.

What I meant is the following:
Within ICPState::isTerminationConditionReached, within the isTargetDiameter reached part, do the following:
Replace
 currentDiameter > Settings::targetDiameter
With
currentRelativeDiameter > Settings::targetDiameter
where
currentRelativeDiameter =  currentDiameter / max(abs(lower), abs(upper))

For example, if the current Interval is [900,1000], then the current diameter is 100, we divide that by the larger of the bounds, i.e. 1000, so we get a relative diameter of 0.1.

**Comment by Verdict7** [comment]
@DavidWz I don't really agree with you here. In your example an interval [0,0.00001] (or any interval starting from 0) would have a relative diameter of 1, right? And might only be improved by splitting (e.g. getting rid of the 0 as one of the bounds).
Also the interval [900,1000] would be closer to the target than [0,100], even though they have the same diameter... Is this really what you are trying to achieve?

**Comment by kperun** [comment]
This is exactly my thought. Whenever we have one of the bounds equal to 0, we would result in a relative diameter of 1, which would lead to a situation where we do not terminate.

**Comment by kperun** [comment]
I have reverted my update in the last push, now we have the old system where we consider an absolute value as target diameter.

**Comment by DavidWz** [comment]
You are right, I think this idea in general might be not that good.
Idea abandoned, issue closed.
