### ISSUE TITLE
get best splitting variable bug

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#49]
The last commit 8f66568d49582d0e9caee37ea3a71c84a5e491cd addresses this issue, but looks more like a hack than a solution. The problem seems to be that no suitable variable is found when looking at only unsat constraints.

**Comment by Verdict7** [comment]
The reason why the previous version returned NO_VARIABLE is probably due to the fact that infinite intervals have a diameter of 0. 
This requires some extra discussion, since we currently assume that no variables are completely unbounded in the beginning. Also: If there is an unbounded variable, should it be chosen for the split or not?

**Comment by kperun** [comment]
@Verdict7 I will take a closer look at this in the next few days. Currently, this approach works but is rather (as you already said) "hacky" and should not be present in the later releases.

**Comment by Verdict7** [comment]
As long as guessSolution is deterministic this function should work. 
The reason this issue was labelled as a bug is, that I was unsure whether there might be an additional problem, but since that does not seem to be the case, this issue will now be closed.
