### ISSUE TITLE
No distinction between active and non-active variables 

### ISSUE THREAD

**Issue by kperun** [kperun/SATPrakPDW#50]
Currently, we see all variables which have been extracted during the informCore() call as the variables of our current problem. However, when certain variables only occur in a subset of constraint which is currently not active, it does not make sense to check if the boundaries of these variables are fulfilled. Here, we probably should also store the current active variables.

**Comment by DavidWz** [comment]
There are always constraints of the form
-1000 < x < 1000
so every variable is always active.
