### ISSUE TITLE
Segfaults 

### ISSUE THREAD

**Issue by kperun** [kperun/SATPrakPDW#51]
The benchmark shows that, in some cases, segfaults and memouts occure. The following problems contained segfaults:
/hycomp/ball_count_2d_hill.01.redlog_global_15.smt2
/hycomp/ball_count_2d_hill.03.redlog_global_14.smt2
hycomp/ball_count_2d_hill.03.redlog_global_15.smt2
/hycomp/ball_count_2d_hill.05.redlog_global_14.smt2
/hycomp/ball_count_2d_hill.05.redlog_global_15.smt2
/hycomp/ball_count_2d_hill.10.redlog_global_14.smt2
hycomp/etcs_braking_2.01.redlog_global_14.smt2
hycomp/etcs_braking_2.01.redlog_global_15.smt2
hycomp/simple_ballistics_reach.01.seq_lazy_lemmas_global_14.smt2
meti-tarski/Arthan/1A/Arthan1A-chunk-0021.smt2
meti-tarski/atan/problem/2/atan-problem-2-chunk-0011.smt2
meti-tarski/atan/problem/2/atan-problem-2-chunk-0012.smt2
meti-tarski/atan/problem/2/atan-problem-2-chunk-0109.smt2
meti-tarski/atan/problem/2/weak/atan-problem-2-weak-chunk-0009.smt2
meti-tarski/atan/problem/2/weak/atan-problem-2-weak-chunk-0010.smt2
meti-tarski/polypaver/sqrt-circles/2a/polypaver-sqrt-circles-2a-chunk-0015.smt2

**Comment by kperun** [comment]
After some sample tests, it seems that the segfaults do not occur in every execution. On my machine, the execution of e.g. atan-problem-2-weak-chunk-0010 did not contain any errors or segfaults. @DavidWz and @Verdict7 would you mind testing the stated problems?

**Comment by DavidWz** [comment]
I tested the meti-tarski problems and got SAT in all cases. Never segfaults.
However, I couldn't find the hycomp examples. I think they are using a different set of benchmark examples? The files also don't have "bounded" in their names, so are they using unbounded versions? We have to ask them.

**Comment by kperun** [comment]
Moreover, the timeframe in which a problem has to be solved is limited (if I recall correctly it was 30 seconds), as well as the amount of memory (4 gigs). However, I think this is something that we can not actively test. We should desist from using an artificial limitation of the maximal computation time, but use, as @DavidWz  already mentioned, an indirect limitation, e.g. by setting the number of splits etc.

**Comment by DavidWz** [comment]
I looked at the segfaults in the latest benchmark, and again, I cannot reproduce any of them. I always get sat or unsat.
@kperun Do you have an example problem which leads to a segfault?

**Comment by DavidWz** [comment]
Okay, the segfaults happened not in the bounded.zip examples but in their QF_NRA examples.
I could reproduce them and fixed a lot of them in commit 0ac5bcf.
