### ISSUE TITLE
Create a method which calls the backend

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#56]
Instead of returning unknown in `ICPPDWModule::checkCore` at line 416-423, ask the backend instead. To this end, do the following:

Create a method `Answer ICPPDWModule::callBackend(ICPTree<Settings>* currentNode)` and call it in `ICPPDWModule::checkCore` instead of the debug output `returning unknown`. If the return value of that call is SAT, return SAT in `checkCore` as well.  If it is UNSAT, add debug output for `current state is unsat`. If it is unknown, add debug output for `current state is unknown` (but do not return unsat or unknown, since we still need to check other nodes after that).

Inside the `callBackend` method itself, we need to ask the backend to check the core. In principle, this has to be done the following way:
1. For every original variable, call  `intervalToConstraint(currentNode->getCurrentState().getInterval(originalVariable))` and pass those constraints to the backend via `addSubformulaToPassedFormula()`
3. Call the backend with `runBackends(...)`
4. If the answer was SAT, update our model by calling `updateModel()`.
5. Call `eraseSubformulaFromPassedFormula()` with all of the constraints from step 1.

**Comment by DavidWz** [comment]
For the third step: I found out how to call the backend.
See SATModule.cpp for further details, but essentially you just have to call `runBackends(...)` with appropriate parameters. You will get the answer as a return value.

If the backend returned Sat, you set the model by simply calling `updateModel()`, I think.

**Comment by kperun** [comment]
@DavidWz  done. Still, there are several questions left open. What happens if the backend returns UNSAT or UNKNOWN? What does it mean? There exists a method getInfeasibleSubsets(), but it leads it a segfault. Moreover, I  am not sure if all used parameters of runBackends() are correct (I did not use any at all). Please review the code and close the issue if it is correct.

**Comment by DavidWz** [comment]
If it returns UNSAT, then issue #57 will handle that.
If it returns UNKNOWN, then... it's still unknown and we simply do nothing.
I am also not sure which parameters to use for runBackends(), but it seems to be working just fine.
Issue closed.
