### ISSUE TITLE
Add support for iterative calls to the backend

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#57]
After issue #56 is resolved, we need to handle the infeasable subset returned by the backend.
To this end, create a method `handleBackendUnsat(...)`to `ICPTree` with parameters containing the conflict reasons (maybe mInfeasableSubset?, but from the backend).
During the `handleBackendUnsat` method, initialize mConflictingConstraints and mConflictingVariables, then call handleUnsat as usual.

**Comment by kperun** [comment]
@DavidWz in order to retrieve the infeasible set from the backends, take a look at Module.cpp (lines 644-657). There, this behavior is already implemented and illustrates the overall procedure quite good.

**Comment by DavidWz** [comment]
@kperun Thanks, I had to copy that code and tweak it a little bit so that we don't use origins (that's where the segfault came from).
Backend call is fully implemented now.
