### ISSUE TITLE
Heuristics for choosing next subtree

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#65]
Right now we choose the tree that satisfies _the most_ constraints. 
This is a strategy that tries to prove, and therefore prefers, SAT (this can be seen in the shorter times it takes to solve SAT problems, also the fact we solve more SAT instances).
Maybe we can do the following: 
`#abs(satisfiedConstraints - (alpha * #constraints / 2))`. 
If the above equation is negative it is more likely that the problem is UNSAT. 
Since we can only prove UNSAT for the current subtree, we use alpha in (0,1) to still prefer SAT solutions.
Any further ideas would be appreciated.

**Comment by kperun** [comment]
@Verdict7 Done. However, the implemented version regards only the number of initial constraints, thus the "slack" constraints are not regarded. Moreover, we need to somehow figure out a good value for the alpha parameter.
