### ISSUE TITLE
Use optional or variant for optional results

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#8]
As of now, we use pair<Interval, Interval> for getContractedInterval() in ICPContractionCandidate, and vector<vector<ConstrainT>> for mAppliedIntervalConstraints in ICPState.

However, in both of these cases, the actual type can only be either one or two elements.

Create a typedef / class called OneOrTwo<T> (e.g. variant<T, pair<T, T>> or  pair<T, optional<T>>).
Then, replace the result type of getContractedInterval with OneOrTwo<Interval> and the type of mAppliedIntervalConstraints with vector<OneOrTwo<ConstraintT>>.

Don't forget to adjust the usage in ICPPDWModule.

**Comment by Verdict7** [comment]
Added typedef OptionalInterval that uses a pair of IntervalT and (experimental) optional<IntervalT> and changed all present calls of getContractedInterval to use the new type.
ICPTree uses an out-stream that stopped working though.
