### ISSUE TITLE
Implement termination conditions

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#9]
Since ICP is incomplete, we need to decide when to stop contracting.

Implement termination conditions in ICPState::isTerminationConditionReached.
Two conditions come to mind: 
1. Maximal number of iterations (already implemented)
2. Target diameter reached for all intervals

**Comment by kperun** [comment]
@DavidWz completed, now whenever either the maximal number of iterations has been done, or all intervals have achieved the desired diameter, the method returns true. Please review the code if possible.
